import type { Metadata } from "next";
import { ReactNode } from 'react';
import { Inter } from "next/font/google";
import "./globals.css";
import "./component/Layout/layout.css"
import Link from 'next/link';
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
    <head>
      <title>My Next.js App</title>
    
    </head>
    <body>
      <header>
     
      <nav>
          <ul>
            <li><a href="/about">About Us test</a></li>
            <li><a href="/contact">Contact Us test</a></li>
          </ul>
        </nav>
  
      </header>
      <main>
      <div className="context">
      {children}
    </div>
      <div className="area" >
            <ul className="circles">
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                    <li></li>
                   
            </ul>
    </div >
       
      </main>
      <footer>
        <p>&copy; 2024 My Next.js App</p>
      </footer>
    </body>
  </html>
  );
}
